### PR TITLE
Add Reddit social icon

### PR DESCRIPTION
**Pull request by Y-T-G**
Downloaded from [FontAwesome](https://fontawesome.com/icons/reddit-alien?f=brands&s=solid).

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Y-T-G @Burhan-Q thanks guys! We need to use the "Dark Blue" color for all logos from https://www.ultralytics.com/brand, this one will stick out with the wrong color as is currently.

Please update the logo with the color from the brand page. Thank you!

**Comment by glenn-jocher** [comment]
Hex is `#111F68`

https://www.ultralytics.com/brand
Screenshot 2024-08-08 at 18 47 40

**Comment by Y-T-G** [comment]
@glenn-jocher Alright, updated.

**Comment by Y-T-G** [comment]
The other logos here aren't `#111F68`

image

The Reddit one:

image

**Comment by Burhan-Q** [comment]
I took a quick sample and looks like the correct color to match the majority of icons should be `#0b23a9`. I'm also seeing that the YouTube icon probably needs to get updated with the correct color as it's _slightly_ different from the others. I also confirmed with another color picker that the values are consistent just b/c I wanted to be certain.

image
image
image
image
image

@glenn-jocher I'm going to assume all the icons should keep the `#0b23a9` color and not use the `#111F68` as they currently aren't using this. I'll assume that's the case unless hearing otherwise. 

I'd guess the reason for this color (`#0b23a9`) is so that the icons will stand out more on dark mode, as the "Dark blue" color would make them less visible, but that's only my speculation. From the docs page in dark mode:

## Using `#0b23a9`
image

## Using `#111F68`
dark-icons

**Comment by glenn-jocher** [comment]
@Burhan-Q ah, good catch. Yes let's do the Reddit icon in #0b23a9 then for consistency.

**Comment by Burhan-Q** [comment]
I see the icon has been updated to use `#0b23a9` so I'm going to merge

**Pull request merged**
